### PR TITLE
Update version to 1.3.1

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by astrofrog** [comment]
@bsipocz - the md5 should be updated too

**Comment by bsipocz** [comment]
Ouch, I meant to create the branch on my fork rather than here. Apparently it's not obvious from the browser...

**Comment by mwcraig** [comment]
Removing the numpy patch should fix the builds, will kill the branch/push builds if I can...

**Comment by bsipocz** [comment]
Thanks @mwcraig. I meant to come back to this, but it's great to see you already fixed the fails.

**Pull request merged**
