### PR TITLE
Updating astropy to 2.0.4

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
@conda-forge-admin, please rerender

**Comment by bsipocz** [comment]
@mwcraig - Do you think we can do anything about the failing appveyor builds here, or it's purely an upstream issue? I see similar failures reported with previous numpy versions where it seemed that the issue is with the wheels provided, e.g. https://github.com/numpy/numpy/issues/9272

**Comment by bsipocz** [comment]
I'm very much inclined to get this merged as is now rather than try to figure out what goes wrong in the appveyor builds. At least we can have most of the architectures covered.

**Comment by astrofrog** [comment]
It might be worth asking about the AppVeyor failures on the conda-forge gitter channel

**Comment by isuruf** [comment]
cc @xoviat

**Comment by xoviat** [comment]
Isn't this a noarch package?

**Comment by mwcraig** [comment]
No, it needs to build several cython/c extension

**Pull request closed without merging**
