### PR TITLE
add patch for creating invalid compressed test data on fly

### PR DESCRIPTION
**Pull request by msarahan**
More info at https://github.com/astropy/astropy/pull/6522

### CODE REVIEW

**Comment by bsipocz** [comment]
I'm :-1 on this for various reasons:

* the referenced PR is not yet merged.
* would rather have conda packaged versions for released version only. With this approach we could add a patch for every bugfix. I don't yet have an ETA for the new bugfix release, but probably will do one later this month.

* a simple workaround for the antivirus issue is to simply delete those test files. Surely that will mess a bit up a few tests, but that shouldn't be much of a concern for a user.

**Comment by msarahan** [comment]
No problem.  We're putting this patch into the anaconda package, but it need not apply here.  I only put up this PR for the sake of keeping things matched up.

**Comment by bsipocz** [comment]
That case I would rather try to do a 2.0.2 release tomorrow :)

**Comment by msarahan** [comment]
That's great!  I'll just ignore this patch on 2.0.1 then and wait for your release.

**Pull request closed without merging**
