### PR TITLE
6.1.1 build 1

### PR DESCRIPTION
**Pull request by mwcraig**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Review by bsipocz — APPROVED** [review]

**Comment by pkgw** [comment]
Yes, this looks correct to me.

Cross-refs for posterity:

- https://github.com/conda-forge/astropy-feedstock/issues/140
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/803

**Comment by pkgw** [comment]
Oh, but: probably good to add a comment to the new constraint mentioning that it is only expected to be needed for 6.1.1, and it should be removed upon the next release. Or add it to the package version specification so that it will be prominent in the diff when the robot PR comes in.

**Comment by neutrinoceros** [comment]
@mwcraig I came here to say that we shouldn't need to invent version numbers for conda but that's not what you're actually doing, so could you edit the title of the PR to "astropy 6.1.1: build 1" for posterity ?

**Comment by bsipocz** [comment]
New release is out, so I expect the bot to pick a new PR up in a few hours...

**Pull request merged**
