### PR TITLE
DONOT MERGE -- Bump build number as part of a re-render

### PR DESCRIPTION
**Pull request by mwcraig**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwcraig** [comment]
@conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
> Hi! This is the friendly automated conda-forge-webservice.
>
> I tried to re-render for you, but it looks like there was nothing to do.

So much for that idea....

**Comment by mwcraig** [comment]
@bsipocz -- are you able to rerender this locally? I'm hitting an error when I try...

**Comment by astrofrog-conda-forge** [comment]
This worked in #51, so closing this

**Pull request closed without merging**
