### PR TITLE
Updating astropy 2.0.10

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
While the builds passed here before merge, somehow neither the OSX nor the windows versions are available for 2.0.10 or in fact 2.0.9.

@mwcraig - any ideas? Also, 2.0.10 hasn't been picked up and copied over to the astropy channel. should we do it by hand?

**Comment by mwcraig** [comment]
Odd; I’ll be able to look tonight. It looks like Linux builds of 2.0.10 have transferred now but none of the others....

**Comment by bsipocz** [comment]
It's not urgent as I'll have to do 2.0.11 pretty soon anyway and will try to get it on defaults, too.

**Comment by mwcraig** [comment]
I think this branch needs a re-render; several have been done on the master branch since this left master. The fails are happening during the upload, which only happens when the PR is merged, so the checks. Going to open a PR in a moment that bumps the build number on this branch, then ask the bot to re-render the PR.

**Comment by mwcraig** [comment]
One other minor thing -- looks like the build number on the first release of 2.0.10 was 1, should have been zero. Bumping it to 2 in the new PR....

**Pull request merged**
