### PR TITLE
Astropy 204

### PR DESCRIPTION
**Pull request by xoviat**
Closes gh-21.

### CODE REVIEW

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender.

**Comment by xoviat** [comment]
@conda-forge/astropy This is ready to merge.

**Comment by bsipocz** [comment]
Many thanks @xoviat!

**Comment by mwcraig** [comment]
Thanks, @xoviat!

**Pull request merged**
