### PR TITLE
 Move pytest-astropy from run to test dependency

### LINKED ISSUE #54: pytest-astropy should probably not be a run dependency
This broke a CI chain of ours because `pytest` was installed in a too old version by conda which our `test-requirements.txt` could not fix since it uses pip for installing the test requirements. We have fixed our CI script but I think that `pytest` should not be a run requirement since it can break how the tests of downstream packages are run.

e.g.:

```bash
$ conda create -n astropy_pytest python=2.7 astropy

Solving environment: done

## Package Plan ##

  environment location: /home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/astropy_pytest

  added / updated specs: 
    - astropy
    - python=2.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astropy-2.0.11             |py27h14c3975_1000         6.7 MB  conda-forge
    blas-1.0                   |              mkl           6 KB
    ------------------------------------------------------------
                                           Total:         6.7 MB

The following NEW packages will be INSTALLED:

    astropy:         2.0.11-py27h14c3975_1000 conda-forge
    atomicwrites:    1.2.1-py_0               conda-forge
    attrs:           18.2.0-py_0              conda-forge
    blas:            1.0-mkl                             
    ca-certificates: 2018.11.29-ha4d7672_0    conda-forge
    certifi:         2018.11.29-py27_1000     conda-forge
    funcsigs:        1.0.2-py_3               conda-forge
    intel-openmp:    2019.1-144                          
    libffi:          3.2.1-hf484d3e_1005      conda-forge
    libgcc-ng:       7.3.0-hdf63c60_0         conda-forge
    libgfortran-ng:  7.2.0-hdf63c60_3         conda-forge
    libstdcxx-ng:    7.3.0-hdf63c60_0         conda-forge
    mkl:             2019.1-144                          
    mkl_fft:         1.0.10-py27h470a237_1    conda-forge
    mkl_random:      1.0.2-py27_0             conda-forge
    more-itertools:  4.3.0-py27_1000          conda-forge
    ncurses:         6.1-hf484d3e_1002        conda-forge
    numpy:           1.15.4-py27h7e9f1db_0               
    numpy-base:      1.15.4-py27hde5b4d6_0               
    openssl:         1.0.2p-h14c3975_1002     conda-forge
    pip:             18.1-py27_1000           conda-forge
    pluggy:          0.6.0-py_0               conda-forge
    py:              1.7.0-py_0               conda-forge
    pytest:          3.6.4-py27_0             conda-forge
    python:          2.7.15-h938d71a_1006     conda-forge
    readline:        7.0-hf8c457e_1001        conda-forge
    setuptools:      40.6.3-py27_0            conda-forge
    six:             1.12.0-py27_1000         conda-forge
    sqlite:          3.26.0-h67949de_1000     conda-forge
    tk:              8.6.9-h84994c4_1000      conda-forge
    wheel:           0.32.3-py27_0            conda-forge
    zlib:            1.2.11-h14c3975_1004     conda-forge

Proceed ([y]/n)? 

```

### PR DESCRIPTION
**Pull request by dstansby**
Fixes #54 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by bsipocz** [comment]
I'm not sure we want to do rebuild the conda packages, rather than start doing this from 4.0. 

Note that the default channel is also distributing astropy, so things would end up inconsistently by merging this with the bumped build number.

**Comment by dstansby** [comment]
👍 sounds good to me. I wasn't sure which one was right to send the PR to, so I sent it to both. At least we know that all the testing works with this change now, so it can be included with the next release.

**Comment by bsipocz** [comment]
what do you mean by "send it to both"?

**Comment by dstansby** [comment]
Sorry, sent it to both channels, ie. I also opened this PR: https://github.com/AnacondaRecipes/astropy-feedstock/pull/2

**Comment by bsipocz** [comment]
Ah, ok, I see, I totally forgot about that one.

**Comment by dstansby** [comment]
Wondering what the status of this is now that 4.0 has been released?

**Comment by bsipocz** [comment]
Thanks @dstansby, indeed this has been forgotten, but I'm merging it now.

**Comment by dstansby** [comment]
Thanks!

**Pull request merged**
