### PR TITLE
DO NOT MERGE -- test run of building astropy 4.1

### PR DESCRIPTION
**Pull request by mwcraig**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwcraig** [comment]
@conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
@astrofrog @eteq -- good news/bad news. This builds, but the parallel tests for the fast ascii reader take roughly forever (2.5 hours) to run on Windows and on OSX/python 3.8. 

I can reproduce the OSX behavior on my mac, and these tests seem slower in python 3.8 built with pip as well as conda (though a bit slower in the could-built version, and glacial in testing run by conda-build).

This particular set of tests (parallel fast reader test) is always skipped on travis by [this](https://github.com/astropy/astropy/blob/399f7e11f6bef114ae0aa507cc6db8d8fead0534/astropy/io/ascii/tests/test_c_reader.py#L74); I can force an xfail in the recipe or drop this set of test from the recipe. 

Current inclination: Open an issue about this in astropy, remove the slow tests from the recipe.

**Comment by astrofrog** [comment]
@mwcraig - I think the issue you are running into is https://github.com/astropy/astropy/issues/9864 - it's not anything new in the last few months but more new in Python 3.8. However, the level of slow you are seeing is at another level! I would suggest to comment on that issue about the performance you are seeing, and then just patch-skipping those tests in the conda recipe for now?

**Comment by mwcraig** [comment]
I think this is ready to go for 4.1. It simply skips the slow `io.ascii` tests for now.

I assume that LTS will change to 4.0.x once 4.1 is released?

**Comment by mwcraig** [comment]
@astrofrog-conda-forge -- I'll update the SHA for this release in a moment. The mismatch is causing the current fails

**Comment by mwcraig** [comment]
@conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
Closed in favor of #74

**Pull request closed without merging**
