### PR TITLE
Yet another Python 39 rebuild

### PR DESCRIPTION
**Pull request by Anthchirp**
Closes #80, closes #79, closes #78

Builds on top of the other Python 3.9 PRs, but adds the missing dependency (cf. discussion in #80) 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
https://github.com/conda-forge/pytest-doctestplus-feedstock/pull/13

**Comment by Anthchirp** [comment]
@conda-forge/astropy tests pass, this is ready for review/merging

**Comment by bsipocz** [comment]
Why does the build number need to be bumped? Would be great if this would provide the 39 builds, but is there a reason to rebuild the rest?

**Comment by Anthchirp** [comment]
Incrementing the build number doesn't have any real drawbacks, but allows distinguishing between builds.

Equally, if you rebuild with the same build number it becomes less clear what builds you get and what their provenance was.

**Comment by Anthchirp** [comment]
-> https://conda-forge.org/docs/maintainer/updating_pkgs.html#bumping-the-build-number

**Comment by bsipocz** [comment]
But here I see no reasons to rebuild the previously available versions. This should provide the updates for getting py39 alone 🤷 

Anyway, I'm leaving this PR up to @mwcraig.

**Comment by mwcraig** [comment]
Thought about this for a while and I think it is better to bump the build number -- I see that as essentially an internal conda thing and would prefer not to end up  with some of build number `1` having `setuptools` as a runtime dependency and some not. Bumping will burn some CI time but seems otherwise harmless.

**Comment by bsipocz** [comment]
My thinking was that users shouldn't pick up an update just because we now build py39...

**Pull request merged**
